INSERT INTO USER (ID,VERSION, USERNAME, EMAIL, PASSWORD, ROLE) VALUES (0, 0, 'admin', 'admin@gmail.com', 'admin', 'ADMIN');
INSERT INTO USER (ID,VERSION, USERNAME, EMAIL, PASSWORD, ROLE) VALUES (1, 1, 'user', 'user@gmail.com', 'user', 'USER');
INSERT INTO USER (ID,VERSION, USERNAME, EMAIL, PASSWORD, ROLE) VALUES (2, 2, 'mod', 'mod@gmail.com', 'mod', 'MODERATOR');
INSERT INTO RECEPT (ID,VERSION, NAME, STATUS, TEXT, USER_ID) VALUES (0, 0, 'recept', 'PUBLIC', 'fffbfbbf', '1');
INSERT INTO RECEPT (ID,VERSION, NAME, STATUS, TEXT, USER_ID) VALUES (3, 3, 'receptpending', 'PENDING', 'fffbfbbf', '2');


